name: Deploy to prod environment

on:
    push:
        branches: 
            - "prod" 


jobs:
    re-deploy-to-prod:
        name: Redploy changes to prod environment
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "SSH into machine, pull and build all the code files and start pm2"
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSHKEY }}" &> ~/.ssh/ssh_key_prod
                sudo chmod 700 ~/.ssh
                sudo chmod 600 ~/.ssh/ssh_key_prod
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh_key_prod root@159.89.84.52 -t "
                cd monorepo-deploy-ci && git pull
                sudo npm install pnpm -g
                pnpm install
                cd packages/db
                pnpm install
                echo "${{ secrets.DB_SECRET_PROD }}" &> .env
                cd ../..
                pnpm install
                pm2 restart all"
